apiVersion: apiconnect.ibm.com/v1beta1
kind: APIConnectCluster
metadata:
  name: apis-minimum
  labels:
    app.kubernetes.io/instance: apiconnect
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: apiconnect-minimum
  namespace: ibm-api-connect-instance
spec:
  license:
    accept: true
    license: "L-RJON-BUVMQX	"
    use: "nonproduction"
  analytics:
    storage:
      enabled: true
      type: unique
  profile: n1xc7.m48
  version: 10.0.3.0