apiVersion: portal.apiconnect.ibm.com/v1beta1
kind: PortalCluster
metadata:
  name: portal
  labels:
    app.kubernetes.io/instance: portal
    app.kubernetes.io/managed-by: ibm-apiconnect
    app.kubernetes.io/name: portal
  namespace: ibm-api-connect-instance
spec:
  license:
    accept: true
    license: "L-APEH-BSVCHU"
    use: "nonproduction"
  databaseVolumeClaimTemplate:
    storageClassName: block-storage
    volumeSize: 300Gi
  certManagerIssuer:
    name: selfsigning-issuer
    kind: Issuer
  webVolumeClaimTemplate:
    storageClassName: block-storage
    volumeSize: 200Gi
  profile: n1xc2.m8
  adminVolumeClaimTemplate:
    storageClassName: block-storage
    volumeSize: 20Gi
  microServiceSecurity: certManager
  databaseLogsVolumeClaimTemplate:
    storageClassName: block-storage
    volumeSize: 12Gi
  portalUIEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts:
      - name: ptl1.apps.apiconnect.example.com
        secretName: portal-web-endpoint-secret
  version: 10.0.3.0
  portalAdminEndpoint:
    annotations:
      certmanager.k8s.io/issuer: ingress-issuer
    hosts:
      - name: ptladmin1.apps.apiconnect.example.com
        secretName: portal-admin-endpoint-secret
  backupVolumeClaimTemplate:
    storageClassName: block-storage
    volumeSize: 300Gi
  adminClientSubjectDN: 'CN=portal-admin-client,O=cert-manager'